### ISSUE TITLE
res folder doesn't exist

### ISSUE THREAD

**Issue by flyingmate** [osmangoninahid/Android-Material-Design-Template#4]
Build failed.. Can you include the res folder?

**Comment by osmangoninahid** [comment]
ok I'll but right now I'm on the way when I back to home then.

**Comment by flyingmate** [comment]
Thank you :)

**Comment by osmangoninahid** [comment]
you are welcome

**Comment by UsmanMalik** [comment]
Please add the res folder.

**Comment by osmangoninahid** [comment]
okay i'll add it ASAP , It was an old project template , I'll make a new one .

**Comment by UsmanMalik** [comment]
Thanks a lot .

**Comment by osmangoninahid** [comment]
In this weekend I'll do it , with some other feature because i lost this source

**Comment by osmangoninahid** [comment]
Hey guys I'm closing this issue, I'm adding `res` folder into repository .
